export const containerList = [
  {
    label: 'REGULAR SIZED CARGO',
    options: [
      {
        "bookableFlag": true,
        "sizeTypeName": "20 DRY",
        "sizeTypeDisplayName": "20 Dry Standard",
        "typeCd": "DRY",
        "displayOrder": "10",
        "sizeCd": "20",
        "activeFlag": true,
        "reeferFlag": false,
        "shipperOwnedFlag": false,
        "carrierOwnedFlag": true,
        "outOfGaugeCargoFlag": false,
        "unitOfMeasurementAbbreviationVal": "8 6",
        "isoContainerSizeTypeName": "ISO Code",
        "isoContainerSizeTypeCd": "22G1",
        "profileName": "",
        "payloadWeight": "28178",
        "payloadWeightUnits": "KGS",
        "tareWeight": "2269",
        "tareWeightUnits": "KGS"
      },
      {
        "bookableFlag": true,
        "sizeTypeName": "40 DRY",
        "sizeTypeDisplayName": "40 Dry Standard",
        "typeCd": "DRY",
        "displayOrder": "20",
        "sizeCd": "40",
        "activeFlag": true,
        "reeferFlag": false,
        "shipperOwnedFlag": false,
        "carrierOwnedFlag": true,
        "outOfGaugeCargoFlag": false,
        "unitOfMeasurementAbbreviationVal": "8 6",
        "isoContainerSizeTypeName": "ISO Code",
        "isoContainerSizeTypeCd": "42G1",
        "profileName": "",
        "payloadWeight": "28045",
        "payloadWeightUnits": "KGS",
        "tareWeight": "3820",
        "tareWeightUnits": "KGS"
      },
      {
        "bookableFlag": true,
        "sizeTypeName": "40 HIGH",
        "sizeTypeDisplayName": "40 Dry High",
        "typeCd": "HDRY",
        "displayOrder": "30",
        "sizeCd": "40",
        "activeFlag": true,
        "reeferFlag": false,
        "shipperOwnedFlag": false,
        "carrierOwnedFlag": true,
        "outOfGaugeCargoFlag": false,
        "unitOfMeasurementAbbreviationVal": "9 6",
        "isoContainerSizeTypeName": "ISO Code",
        "isoContainerSizeTypeCd": "45G1",
        "profileName": "",
        "payloadWeight": "28102",
        "payloadWeightUnits": "KGS",
        "tareWeight": "3849",
        "tareWeightUnits": "KGS"
      },
      {
        "bookableFlag": true,
        "sizeTypeName": "45 HIGH",
        "sizeTypeDisplayName": "45 Dry High",
        "typeCd": "HDRY",
        "displayOrder": "40",
        "sizeCd": "45",
        "activeFlag": true,
        "reeferFlag": false,
        "shipperOwnedFlag": false,
        "carrierOwnedFlag": true,
        "outOfGaugeCargoFlag": false,
        "unitOfMeasurementAbbreviationVal": "9 6",
        "isoContainerSizeTypeName": "ISO Code",
        "isoContainerSizeTypeCd": "L5G1",
        "profileName": "",
        "payloadWeight": "27533",
        "payloadWeightUnits": "KGS",
        "tareWeight": "4768",
        "tareWeightUnits": "KGS"
      },
      {
        "bookableFlag": true,
        "sizeTypeName": "20 Tank",
        "sizeTypeDisplayName": "20 Tank",
        "typeCd": "TANK",
        "displayOrder": "50",
        "sizeCd": "20",
        "activeFlag": true,
        "reeferFlag": false,
        "shipperOwnedFlag": true,
        "carrierOwnedFlag": false,
        "outOfGaugeCargoFlag": false,
        "unitOfMeasurementAbbreviationVal": "8 6",
        "isoContainerSizeTypeName": "ISO Code",
        "isoContainerSizeTypeCd": "22T3",
        "profileName": "",
        "payloadWeight": "25115",
        "payloadWeightUnits": "KGS",
        "tareWeight": "3205",
        "tareWeightUnits": "KGS"
      },
      {
        "bookableFlag": true,
        "sizeTypeName": "40 Tank",
        "sizeTypeDisplayName": "40 Tank",
        "typeCd": "TANK",
        "displayOrder": "60",
        "sizeCd": "40",
        "activeFlag": true,
        "reeferFlag": false,
        "shipperOwnedFlag": true,
        "carrierOwnedFlag": false,
        "outOfGaugeCargoFlag": false,
        "unitOfMeasurementAbbreviationVal": "8 6",
        "isoContainerSizeTypeName": "ISO Code",
        "isoContainerSizeTypeCd": "42T3",
        "profileName": "",
        "payloadWeight": "",
        "payloadWeightUnits": "KGS",
        "tareWeight": "",
        "tareWeightUnits": "KGS"
      },
    ]
  },
  // {
  //   label: 'REEFER CONTAINER',
  //   options: [
  //     {
  //       "bookableFlag": true,
  //       "sizeTypeName": "20 REEF",
  //       "sizeTypeDisplayName": "20 Reefer Standard",
  //       "typeCd": "REEF",
  //       "displayOrder": "130",
  //       "sizeCd": "20",
  //       "activeFlag": true,
  //       "reeferFlag": true,
  //       "shipperOwnedFlag": false,
  //       "carrierOwnedFlag": true,
  //       "outOfGaugeCargoFlag": false,
  //       "unitOfMeasurementAbbreviationVal": "8 6",
  //       "isoContainerSizeTypeName": "ISO Code",
  //       "isoContainerSizeTypeCd": "22R1",
  //       "profileName": "STANDARD",
  //       "payloadWeight": "27454",
  //       "payloadWeightUnits": "KGS",
  //       "tareWeight": "2995",
  //       "tareWeightUnits": "KGS"
  //     },
  //     {
  //       "bookableFlag": true,
  //       "sizeTypeName": "40 HCRF",
  //       "sizeTypeDisplayName": "40 Reefer High",
  //       "typeCd": "HREF",
  //       "displayOrder": "140",
  //       "sizeCd": "40",
  //       "activeFlag": true,
  //       "reeferFlag": true,
  //       "shipperOwnedFlag": false,
  //       "carrierOwnedFlag": true,
  //       "outOfGaugeCargoFlag": false,
  //       "unitOfMeasurementAbbreviationVal": "9 6",
  //       "isoContainerSizeTypeName": "ISO Code",
  //       "isoContainerSizeTypeCd": "45R1",
  //       "profileName": "STANDARD",
  //       "payloadWeight": "29718",
  //       "payloadWeightUnits": "KGS",
  //       "tareWeight": "4500",
  //       "tareWeightUnits": "KGS"
  //     },
  //   ]
  // },
  // {
  //   label: 'ODD SIZED CONTAINER',
  //   options: [
  //     {
  //       "bookableFlag": true,
  //       "sizeTypeName": "20 OPEN",
  //       "sizeTypeDisplayName": "20 Open Top",
  //       "typeCd": "OPEN",
  //       "displayOrder": "70",
  //       "sizeCd": "20",
  //       "activeFlag": true,
  //       "reeferFlag": false,
  //       "shipperOwnedFlag": false,
  //       "carrierOwnedFlag": true,
  //       "outOfGaugeCargoFlag": true,
  //       "unitOfMeasurementAbbreviationVal": "8 6",
  //       "isoContainerSizeTypeName": "ISO Code",
  //       "isoContainerSizeTypeCd": "22U1",
  //       "profileName": "",
  //       "payloadWeight": "27882",
  //       "payloadWeightUnits": "KGS",
  //       "tareWeight": "2374",
  //       "tareWeightUnits": "KGS"
  //     },
  //     {
  //       "bookableFlag": true,
  //       "sizeTypeName": "40 STOT",
  //       "sizeTypeDisplayName": "40 Open Top",
  //       "typeCd": "OPEN",
  //       "displayOrder": "80",
  //       "sizeCd": "40",
  //       "activeFlag": true,
  //       "reeferFlag": false,
  //       "shipperOwnedFlag": false,
  //       "carrierOwnedFlag": true,
  //       "outOfGaugeCargoFlag": true,
  //       "unitOfMeasurementAbbreviationVal": "8 6",
  //       "isoContainerSizeTypeName": "ISO Code",
  //       "isoContainerSizeTypeCd": "42U1",
  //       "profileName": "",
  //       "payloadWeight": "27730",
  //       "payloadWeightUnits": "KGS",
  //       "tareWeight": "3907",
  //       "tareWeightUnits": "KGS"
  //     },
  //     {
  //       "bookableFlag": true,
  //       "sizeTypeName": "40 OPEN",
  //       "sizeTypeDisplayName": "40 Open Top High",
  //       "typeCd": "OPEN",
  //       "displayOrder": "90",
  //       "sizeCd": "40",
  //       "activeFlag": true,
  //       "reeferFlag": false,
  //       "shipperOwnedFlag": false,
  //       "carrierOwnedFlag": true,
  //       "outOfGaugeCargoFlag": true,
  //       "unitOfMeasurementAbbreviationVal": "9 6",
  //       "isoContainerSizeTypeName": "ISO Code",
  //       "isoContainerSizeTypeCd": "45U1",
  //       "profileName": "",
  //       "payloadWeight": "28300",
  //       "payloadWeightUnits": "KGS",
  //       "tareWeight": "4101",
  //       "tareWeightUnits": "KGS"
  //     },
  //     {
  //       "bookableFlag": true,
  //       "sizeTypeName": "40 STFL",
  //       "sizeTypeDisplayName": "40 Flat Standard",
  //       "typeCd": "FLAT",
  //       "displayOrder": "100",
  //       "sizeCd": "40",
  //       "activeFlag": true,
  //       "reeferFlag": false,
  //       "shipperOwnedFlag": false,
  //       "carrierOwnedFlag": true,
  //       "outOfGaugeCargoFlag": true,
  //       "unitOfMeasurementAbbreviationVal": "8 6",
  //       "isoContainerSizeTypeName": "ISO Code",
  //       "isoContainerSizeTypeCd": "42P1",
  //       "profileName": "",
  //       "payloadWeight": "42058",
  //       "payloadWeightUnits": "KGS",
  //       "tareWeight": "5109",
  //       "tareWeightUnits": "KGS"
  //     },
  //     {
  //       "bookableFlag": true,
  //       "sizeTypeName": "40 FLAT",
  //       "sizeTypeDisplayName": "40 Flat High",
  //       "typeCd": "FLAT",
  //       "displayOrder": "110",
  //       "sizeCd": "40",
  //       "activeFlag": true,
  //       "reeferFlag": false,
  //       "shipperOwnedFlag": false,
  //       "carrierOwnedFlag": true,
  //       "outOfGaugeCargoFlag": true,
  //       "unitOfMeasurementAbbreviationVal": "9 6",
  //       "isoContainerSizeTypeName": "ISO Code",
  //       "isoContainerSizeTypeCd": "45P3",
  //       "profileName": "",
  //       "payloadWeight": "45869",
  //       "payloadWeightUnits": "KGS",
  //       "tareWeight": "5188",
  //       "tareWeightUnits": "KGS"
  //     },
  //     {
  //       "bookableFlag": true,
  //       "sizeTypeName": "20 STFL",
  //       "sizeTypeDisplayName": "20 Flat",
  //       "typeCd": "FLAT",
  //       "displayOrder": "120",
  //       "sizeCd": "20",
  //       "activeFlag": true,
  //       "reeferFlag": false,
  //       "shipperOwnedFlag": true,
  //       "carrierOwnedFlag": false,
  //       "outOfGaugeCargoFlag": true,
  //       "unitOfMeasurementAbbreviationVal": "8 6",
  //       "isoContainerSizeTypeName": "ISO Code",
  //       "isoContainerSizeTypeCd": "22P1",
  //       "profileName": "",
  //       "payloadWeight": "32340",
  //       "payloadWeightUnits": "KGS",
  //       "tareWeight": "3077",
  //       "tareWeightUnits": "KGS"
  //     },
  //   ]
  // }
]